### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dyenereks** [MarJose123/BackendDeveloperAssessmentComponent#2]
### What happened?

Encountered an issue on installation.

### How to reproduce the bug

add the library to composer.json inside the require:

```
"marjose123/backenddeveloperassessmentcomponent": "dev-main"
```

![image](https://github.com/MarJose123/BackendDeveloperAssessmentComponent/assets/33676841/61033d5c-0acb-4159-af50-f7047de500fa)

### Package Version

1.0

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by MarJose123** [comment]
Hi @dyenereks, I noticed that you add the ` "marjose123/backenddeveloperassessmentcomponent": "dev-main"` to it's `composer.json`, `backenddeveloperassessmentcomponent` is a library/plugin components. 

I would advise you to create a fresh Laravel project  by using this command `composer create-project laravel/larave` and add the ` "marjose123/backenddeveloperassessmentcomponent": "dev-main"` to your laravel project as mentioned in the `README.MD` file, and also  add the `marjose123/backenddeveloperassessmentcomponent` path in your fresh laravel project `composer.json`

e.g.,

```json

"repositories": [
    {
      "type": "path",
      "url": "../path/to/marjose123/backenddeveloperassessmentcomponent"
    }
  ]
```
